steps:

  # Install node packages
  - name: "gcr.io/cloud-builders/npm:latest"
    args: ["install"]
    dir: "bcg-dashboard"

  # Build production package
  - name: "gcr.io/dashboard-300904/ng"
    args: ["build", "--prod"]
    dir: "bcg-dashboard"

  # Deploy to google cloud app engine
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "--version=prod"]
    dir: "bcg-dashboard"
